import type { Metadata } from "next";
import {Karla,Chivo } from "next/font/google";
import "./globals.css";


const chivo = Chivo({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-chivo",
  display: "swap",
});
const karla = Karla({
  variable: "--font-karla",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${chivo.variable} ${karla.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
